plugins {
    id 'fabric-loom'
    id 'maven-publish'
}

loom {
    splitEnvironmentSourceSets()
    silentMojangMappingsLicense()

    unpick {
        enabled = false
    }

    mods {
        "crappy_achievements" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}