pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    // The ID must be 'fabric-loom'. Variables work here in settings.gradle.
    id 'fabric-loom' version "${loom_version}"
}

rootProject.name = "Crappy-Achievements"